### ISSUE TITLE
Site descriptions bug (wrong language + long af)

### ISSUE THREAD

**Issue by IGLADI** [moa-engine/MOA#22]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
[Public version](https://moae.sbs/search)

**How did you install SearXNG?**
Not (Public version)

**What happened?**
I get really long website descriptions and part of it are in another languages (which isn't there once I click on the website)

**How To Reproduce**
go to https://moae.sbs/search and search for "self host ghost" or most other querry's

**Expected behavior**
See SearXNG screenshot

**Screenshots & Logs**
MOA: ![image](https://github.com/moa-engine/MOA/assets/128155180/f2197f20-2603-4b1f-a6f7-75a079157db4)
SearXNG: 
![image](https://github.com/moa-engine/MOA/assets/128155180/085a15ed-5b25-4e86-884f-558e16b45976)

**Comment by mehr32** [comment]
Thanks for the bug report :) If you notice in the bottom part of your screenshot, in MOA, it is the result from two engines, Bing and Google, that's why it is longer. If there is a problem in merging the results, it will be from the searxng side because we have not made any changes in this section. Of course, thanks for your bug report, I'll definitely take a look at the results integration algorithm

**Comment by mehr32** [comment]
> Weird as I also use bing & google as engines on my searXNG instance (form the screenshot) Maybe because I have set a different weight for each on my personal instance I don't have this issue? And then it would try making the description itself and not from those sources and take a random language? Just some taught, hope this helps and good luck ;)

ranslate this message to English: Search engines may offer different results depending on the physical location of their server. Also, the Google Mojeek engine is slightly different with Searxng (minor modifications have been applied to improve the results, which exceptionally entrusts the language detection for the Google engine to the search engine itself. With this change, its results get much closer to Google's). Anyway, it's not a severe problem, it just seems that the rendering of searches does not adhere to the character count range and this should be corrected.

**Comment by IGLADI** [comment]
> > Weird as I also use bing & google as engines on my searXNG instance (form the screenshot) Maybe because I have set a different weight for each on my personal instance I don't have this issue? And then it would try making the description itself and not from those sources and take a random language? Just some taught, hope this helps and good luck ;)
> 
> ranslate this message to English: Search engines may offer different results depending on the physical location of their server. Also, the Google Mojeek engine is slightly different with Searxng (minor modifications have been applied to improve the results, which exceptionally entrusts the language detection for the Google engine to the search engine itself. With this change, its results get much closer to Google's). Anyway, it's not a severe problem, it just seems that the rendering of searches does not adhere to the character count range and this should be corrected.

Oh yeah for the language part you mean because I was using the version hosted by you guys and not mine I had results based on your country's language? This shouldn't be a problem then, taught google would querry back based on the language I searched instead of location.

Character count range should indeed be corrected, will try to see where it's located in the code base after my finals if you guys haven't corrected it in the meanwhile.

**Comment by IGLADI** [comment]
Seems to be fixed for me 👍
![image](https://github.com/moa-engine/MOA/assets/128155180/64f0fc78-4f75-46b9-ae3b-f090baea2f6f)
