### ISSUE TITLE
I can't set as search engine in firefox.

### ISSUE THREAD

**Issue by marek2001** [moa-engine/MOA#24]
When i try to add MOA as as default search engine i got that error
![obraz](https://github.com/moa-engine/MOA/assets/78016853/21895eb5-75a7-4c05-adb4-8855279da0f5)
That is content of opensearch.xml file:
`
<OpenSearchDescription>
<ShortName>MOA</ShortName>
<LongName>SearXNG metasearch</LongName>
<Description>
SearXNG is a metasearch engine that respects your privacy.
</Description>
<InputEncoding>UTF-8</InputEncoding>
<Image type="image/png">
https://moae.sbs/static/themes/simple/img/favicon.png
</Image>
<Url rel="results" type="text/html" method="GET" template="https://moae.sbs/search?q={searchTerms}"/>
<Url rel="suggestions" type="application/x-suggestions+json" method="GET" template="https://moae.sbs/autocompleter?q={searchTerms}"/>
<Url rel="self" type="application/opensearchdescription+xml" method="GET" template="/opensearch.xml?method=GET&autocomplete=brave"/>
<Query role="example" searchTerms="SearXNG"/>
<moz:SearchForm>https://moae.sbs/search</moz:SearchForm>
</OpenSearchDescription>
`
That is on your official instance.

**Comment by mehr32** [comment]
Hello
Thanks for the bug report. Several other people also had this problem. Can you also test with moae.sbs server and let me know the result?

**Comment by marek2001** [comment]
![obraz](https://github.com/moa-engine/MOA/assets/78016853/326afcb1-48ed-49d0-811e-2690e45654ef)
After i press that button that the result:
![obraz](https://github.com/moa-engine/MOA/assets/78016853/5d41799e-04f2-483d-a927-365c80980f21)

**Comment by mehr32** [comment]
Yes, I understand. It seems the problem with searxng has been resolved. I will merge its changes soon, so we'll get the next release. I will let you know.
