### ISSUE TITLE
Search filters don't work with Content-Security-Policy "script-src 'self';"

### ISSUE THREAD

**Issue by Kuuchuu** [moa-engine/MOA#27]
**Version of Moa:**
 - Uranium 0.3

**How did you install Moa?**
 - Docker image

**What happened?**
After securing Moa with `Content-Security-Policy "script-src 'self';"` the filter button fails to work as the inline script is blocked. `Content-Security-Policy "script-src 'self';"` helps significantly with [Observatory](https://observatory.mozilla.org/) grading.

**How To Reproduce**
Add `script-src 'self';` to "Content-Security-Policy" header
Load Moa in Firefox or Vivaldi private, Filter button doesn't function; script blocked.

**Expected behavior**
Clicky filter button. Maybe default filter div to visible and usable rather than invisible so that if inline scripts are blocked it still functions, or filter button script is changed from inline script.

**Screenshots & Logs**
Firefox:
![image](https://github.com/moa-engine/MOA/assets/20036947/eb348e39-30cf-44ed-9dcf-8839b4a6c777)
Firefox Console Output:
```
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'”
Source: toggleBtn(this, 'filters-visible', '.sea… 2 search
```

Vivaldi:
![image](https://github.com/moa-engine/MOA/assets/20036947/221af52a-e9f2-4922-a5e3-c357ad790991)
Vivaldi Console Output:
```
search:368 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

**EDIT**: Just a note, this seems to be primarily a Firefox issue. Firefox blocks the button script from loading while chrome (Vivaldi really, haven't tested in chrome) allows it to work, except for in private/incognito.

**Comment by Kuuchuu** [comment]
I'm testing out a fix. If I can get it working I'll submit a PR

**Comment by mehr32** [comment]
Hello, I hope you have a good day!
Forgive me for the delay in replying. 
We have recently released tin version 0.4 and we will put the Docker version of it on the Docker repository as soon as possible. Based on my testing on Firefox, there was no such problem. 
I will let you know after it is on the server (as well as the Docker repository).

**Comment by Kuuchuu** [comment]
Great! I also noticed this issue applies to the "infobox-more-btn" as well.
![image](https://github.com/moa-engine/MOA/assets/20036947/720b9f47-106b-4e9b-86b5-4c0a49e58cb4)

Looking forward to trying out the new version when it's updated in the Docker repository.

After I iron out some other issues with my server I plan on listing it as a public instance.

**Comment by mehr32** [comment]
> Great! I also noticed this issue applies to the "infobox-more-btn" as well. ![image](https://private-user-images.githubusercontent.com/20036947/333845606-720b9f47-106b-4e9b-86b5-4c0a49e58cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDA3MjEsIm5iZiI6MTcxNjc0MDQyMSwicGF0aCI6Ii8yMDAzNjk0Ny8zMzM4NDU2MDYtNzIwYjlmNDctMTA2Yi00ZTliLTg2YjUtNGMwYTQ5ZTU4Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE2MjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NGRjNDBhYWFjYjE3YmQ2NTM3ZGEwNjIwNTlhZGRjODJhNGVlMDljNzE4NTZmZWIxYzJiYTkwZWExZGVmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ehuPdxpwtCkwz8slUnIRRgcEkXDibW2u2Tw772eaKBk)
> 
> Looking forward to trying out the new version when it's updated in the Docker repository.
> 
> After I iron out some other issues with my server I plan on listing it as a public instance.

Hi again. A new version of the Docker image is now available.
`docker pull moaengine/moa`

**Comment by Kuuchuu** [comment]
Still the same issue with 0.4. I've submitted PR #29 which fixes the CSP header issue.
